gradient_accumulation_steps: 1
max_grad_norm: 1.0
num_train_epochs: -1
model:
  distributed_backend: ddp
  accelerator: cuda
  strategy: deepspeed_stage
  precision: 16
  base_learning_rate: 1e-4
  target: lvdm.models.ddpm3d.LatentDiffusion
  ckptdir: models/t2v/model.ckpt
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: video
    cond_stage_key: caption
    image_size:
    - 32
    - 32
    video_length: 16
    channels: 4
    cond_stage_trainable: false
    conditioning_key: EchoReel
    scale_by_std: false
    scale_factor: 0.18215
    use_ema: false
    logdir: logs

    unet_config:
      target: lvdm.models.modules.openaimodel3d.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: true
        legacy: false
        kernel_size_t: 1
        padding_t: 0
        use_temporal_transformer: true
        temporal_length: 16
        use_relative_position: true
        EchoReel: True
        # use_fp16: false
        
    first_stage_config:
      target: lvdm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: lvdm.models.modules.condition_modules.FrozenCLIPEmbedder